name: deploy-to-azure
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch

env:
    targetEnv: t9dydevops-prod

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURESERVICEPRINCIPAL }}
        - uses: azure/arm-deploy@v1
          with:
            resourceGroupName: ${{ vars.VARRESOURCEGROUP }}
            template: ./ARM-Templates/container-webapp-template.json
            parameters: webAppName=${{ env.targetEnv }}
