# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
      - '.github/workflows/dotnet.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Application/**'
      - '.github/workflows/dotnet.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Restore dependencies
      run: dotnet restore ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj
    - name: Build
      run: dotnet build --no-restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj
    

    - name: Publish .NET application
      run: dotnet publish ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj -o ./publish
      
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/yourappname:tag ./publish
      
    - name: Log in to Azure Container Registry
      run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin
      
    - name: Push Docker image
      run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/yourappname:tag
