name: First Workflow

# This workflow runs manually
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is step 1"
      - name: Step 2
        run: echo "This is step 2"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is step 1"
      - name: Step 2
        run: echo "This is step 2"

  cow:
    needs: job2
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'